/*
-- Query: select id, tipo, descricao, tuss, deletado, valor from tisaude_app.procedimentos where cliente = 3
-- Date: 2022-06-10 11:27
*/
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1,'CONSULTA E/R','CONSULTA EM CONSULTÓRIO (NO HORÁRIO NORMAL OU PREESTABELECIDO)','10101012 CONSULTA EM CONSULTÓRIO (NO HORÁRIO NORMAL OU PREESTABELECIDO)',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (3,'RETORNO','','0 ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (4,'COLPOSCOPIA',NULL,'',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (78,'ECG','ECG convencional de até 12 derivações 22','40101010 ECG CONVENCIONAL DE ATÉ 12 DERIVAÇÕES 22',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (79,'HOLTER','Holter de 24 horas - 3 canais - digital','20102020 HOLTER DE 24 HORAS - 3 CANAIS - DIGITAL',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (80,'MAPA','EMG para monitoração de quimodenervação (por sessão)','40103382 EMG PARA MONITORAÇÃO DE QUIMODENERVAÇÃO (POR SESSÃO)',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (103,'FISIOTERAPIA','fisioterapia','50000438 FISIOTERAPIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (104,'ACUPUNTURA','Acupuntura por sessão','31601014 ACUPUNTURA POR SESSÃO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (105,'CONSULTA PSICOLOGIA!','CONSULTA PSICOLOGIA',' CONSULTA PSICOLOGIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (106,'CONSULTA NUTRIÇÃO','CONSULTA NUTRIÇÃO',' CONSULTA NUTRIÇÃO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (107,'CONSULTA CLÍNICO GERAL','CONSULTA CLÍNICO GERAL',' CONSULTA CLÍNICO GERAL',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (108,'CONSULTA ALERGOLOGIA E MONOLOGIA','consulta ALERGOLOGIA E MONOLOGIA','10101014 CONSULTA ALERGOLOGIA E MONOLOGIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (109,'CONSULTA CIRURGIA PLÁSTICA','CONSULTA CIRURGIA PLÁSTICA','10101012 CONSULTA CIRURGIA PLÁSTICA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (110,'CONSULTA CIRURGIA VASCULAR / ANGIOLOGIA','CONSULTA CIRURGIA VASCULAR / ANGIOLOGIA','10101012 CONSULTA CIRURGIA VASCULAR / ANGIOLOGIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (111,'CONSULTA DERMATOLOGIA','CONSULTA DERMATOLOGIA','10101012 CONSULTA DERMATOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (112,'CONSULTA FONOAUDIOLOGIA','CONSULTA FONOAUDIOLOGIA',' CONSULTA FONOAUDIOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (113,'CONSULTA GASTROENTEROLOGIA','CONSULTA GASTROENTEROLOGIA',' CONSULTA GASTROENTEROLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (114,'CONSULTA GINECOLOGIA E OBSTETRÍCIA','CONSULTA GINECOLOGIA E OBSTETRÍCIA',' CONSULTA GINECOLOGIA E OBSTETRÍCIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (115,'CONSULTA MASTOLOGIA','CONSULTA MASTOLOGIA',' CONSULTA MASTOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (116,'CONSULTA MEDICINA DO TRABALHO','CONSULTA MEDICINA DO TRABALHO',' CONSULTA MEDICINA DO TRABALHO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (117,'CONSULTA OFTALMOLOGIA','CONSULTA OFTALMOLOGIA',' CONSULTA OFTALMOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (118,'CONSULTA ORTOPEDISTA','CONSULTA ORTOPEDISTA',' CONSULTA ORTOPEDISTA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (119,'CONSULTA OTORRINOLARINGOLOGIA','CONSULTA OTORRINOLARINGOLOGIA',' CONSULTA OTORRINOLARINGOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (120,'CONSULTA ONCOLOGISTA ','CONSULTA ONCOLOGISTA',' CONSULTA ONCOLOGISTA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (121,'CONSULTA PEDIATRIA','CONSULTA PEDIATRIA',' CONSULTA PEDIATRIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (122,'CONSULTA PROCTOLOGIA','CONSULTA PROCTOLOGIA',' CONSULTA PROCTOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (123,'CONSULTA UROLOGIA','CONSULTA UROLOGIA',' CONSULTA UROLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (124,'CONSULTA CARDIOLOGIA','CONSULTA CARDIOLOGIA','10101012 CONSULTA CARDIOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (125,'CONSULTA ENDOCRINOLOGIA','CONSULTA ENDOCRINOLOGIA',' CONSULTA ENDOCRINOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (126,'CONSULTA HEMATOLOGIA','CONSULTA HEMATOLOGIA',' CONSULTA HEMATOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (127,'CONSULTA HEPATOLOGIA','CONSULTA HEPATOLOGIA',' CONSULTA HEPATOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (128,'CONSULTA INFECTOLOGIA','CONSULTA INFECTOLOGIA',' CONSULTA INFECTOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (129,'CONSULTA NEFROLOGIA','CONSULTA NEFROLOGIA',' CONSULTA NEFROLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (130,'CONSULTA NUTROLOGIA','CONSULTA NUTROLOGIA',' CONSULTA NUTROLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (131,'CONSULTA MEDICINA ESPORTIVA','CONSULTA MEDICINA ESPORTIVA',' CONSULTA MEDICINA ESPORTIVA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (132,'CONSULTA PNEUMOLOGIA','CONSULTA PNEUMOLOGIA',' CONSULTA PNEUMOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (133,'CONSULTA REUMATOLOGIA','CONSULTA REUMATOLOGIA',' CONSULTA REUMATOLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (134,'CONSULTA GERIATRIA','CONSULTA GERIATRIA',' CONSULTA GERIATRIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (135,'CONSULTA HOMEOPATIA','CONSULTA HOMEOPATIA',' CONSULTA HOMEOPATIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (136,'CONSULTA NEUROLOGIA','CONSULTA NEUROLOGIA',' CONSULTA NEUROLOGIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (137,'CONSULTA PSIQUIATRA','CONSULTA PSIQUIATRA',' CONSULTA PSIQUIATRA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (138,'CHECK UP ESSENCIAL','Check Up Essencial',' CHECK UP ESSENCIAL',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (139,'CHECK UP MASCULINO 39 - ','Check Up Masculino 39 - ',' CHECK UP MASCULINO 39 - ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (140,'CHECK UP FEMININO 39 - ','Check Up Feminino 39 - ',' CHECK UP FEMININO 39 - ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (141,'CHECK UP MASCULINO 40 + ','Check Up Masculino 40 + ',' CHECK UP MASCULINO 40 + ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (142,'CHECK UP FEMININO 40 + ','Check Up Feminino 40 + ',' CHECK UP FEMININO 40 + ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (143,'CHECK UP CARDIOLÓGICO','Check Up Cardiológico',' CHECK UP CARDIOLÓGICO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (144,'PROCEDIMENTOS ODONTOLÓGICOS','PROCEDIMENTOS ODONTOLÓGICOS',' PROCEDIMENTOS ODONTOLÓGICOS',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (145,'ORÇAMENTO ODONTOLÓGICO','ORÇAMENTO ODONTOLÓGICO',' ORÇAMENTO ODONTOLÓGICO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (146,'NOVO PROCEDIMENTO TESTE ADICAO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (147,'BOTOX','botox','123412341234 BOTOX',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (148,'BIOFEEDBACK','Manometria computadorizada anorretal para biofeedback - demais sessões','40102041 MANOMETRIA COMPUTADORIZADA ANORRETAL PARA BIOFEEDBACK - DEMAIS SESSÕES',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (149,'DRENAGEM','DRENAGEM',' DRENAGEM',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (150,'PILATES','PILATES','13106966 PILATES',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (151,'RPG',' Reeducação Postural Global','50000446  REEDUCAÇÃO POSTURAL GLOBAL',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (152,'AGULHAMENTO','AGULHAMENTO',' AGULHAMENTO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (153,'FISIOTERAPIA','FISIOTERAPIA',' FISIOTERAPIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (154,'RPG2',' Reeducação Postural Global','50000446  REEDUCAÇÃO POSTURAL GLOBAL',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (155,'RPG3','RPG','50000446 RPG',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (156,'CONSULTA 1X','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (157,'PACOTE DE DEPILAÇÃO','PACOTE DE DEPILAÇÃO',' PACOTE DE DEPILAÇÃO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (158,'SEÇÃO DE DEPILAÇÃO','SEÇÃO DE DEPILAÇÃO',' SEÇÃO DE DEPILAÇÃO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (159,'CONSULTA 1ª VEZ','CONSULTA 1ª VEZ',' CONSULTA 1ª VEZ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (160,'PROCEDIMENTO TESTE 1','PROCEDIMENTO TESTE 1','147987 PROCEDIMENTO TESTE 1',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (161,'PROCEDIMENTO TESTE 2','PROCEDIMENTO TESTE 2','1236945 PROCEDIMENTO TESTE 2',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (162,'TRATAMENTI]O HC PACOTE','tratamento hc pacote',' TRATAMENTO HC PACOTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (163,'TRATAMENTO HC SEC','TRATAMENTO HC PACOTE sec',' TRATAMENTO HC PACOTE SEC',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (164,'LASER','tratamento de laser',' TRATAMENTO DE LASER',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (165,'PACOTE DE CONSULTA PSICOLÓGICA 2','PACOTE DE CONSULTA PSICOLÓGICA 2',' PACOTE DE CONSULTA PSICOLÓGICA 2',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (166,'SESSÃO PAGA ANTECIPADO','SESSÃO PAGA ANTECIPADO',' SESSÃO PAGA ANTECIPADO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (167,'TESTE VERUSKA','teste',' TESTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (168,'CONSULTA DE AVALIAÇÃO','CONSULTA DE AVALIAÇÃO',' CONSULTA DE AVALIAÇÃO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (169,'TELEOFTALMOLOGIA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (170,'PILATES 2 X MENSAL','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (171,'AULA EXPERIMENTAL PILATES','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (172,'RECONSTRUÇÃO TOTAL DO LÁBIO','Reconstrução total do lábio','30201098 RECONSTRUÇÃO TOTAL DO LÁBIO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (173,'TRATAMENTO CIRÚRGICO DA MACROSTOMIA','Tratamento cirúrgico da macrostomia','30201101 TRATAMENTO CIRÚRGICO DA MACROSTOMIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (174,'TRATAMENTO CIRÚRGICO DA MICROSTOMIA','Tratamento cirúrgico da microstomia','30201110 TRATAMENTO CIRÚRGICO DA MICROSTOMIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (175,'ALONGAMENTO CIRÚRGICO DO PALATO MOLE','Alongamento cirúrgico do palato mole','30202019 ALONGAMENTO CIRÚRGICO DO PALATO MOLE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (176,'BIÓPSIA DE BOCA','Biópsia de boca','30202027 BIÓPSIA DE BOCA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (177,'EXCISÃO DE TUMOR DE BOCA COM MANDIBULECTOMIA','Excisão de tumor de boca com mandibulectomia','30202043 EXCISÃO DE TUMOR DE BOCA COM MANDIBULECTOMIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (178,'TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (179,'CESARIA','CESARIA',' CESARIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (180,'TESTE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (181,'PROCEDIMENTOS ODONTOLOGICOS','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (182,'PROTOCOLO DE VERÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (183,'ULTRASSOM','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (184,'DENTISTA','dentista',' DENTISTA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (185,'PACOTE 1','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (186,'EXCLEROTERAPIA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (187,'TELECONSULTA TESTE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (188,'PROCEDIMENTO TESTE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (189,'','colonoscopia','70191491 COLONOSCOPIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (190,'CONSULTA APCEF','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (191,'CONSULTA APCF','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (192,'ULTHERA FACE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (193,'BOTOX','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (194,'PACOTE VELA SHAPE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (195,'TEMPO DE DURAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (196,'CONSULTA GINECOLOGISTA','CONSULTA GINECOLOGISTA',' CONSULTA GINECOLOGISTA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (197,'RETORNO + 300 DIAS','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (198,'CONSULTA FISIOTERAPEUTA','CONSULTA FISIOTERAPEUTA DESCRIÇÃO','1254896 CONSULTA FISIOTERAPEUTA DESCRIÇÃO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (199,'RETIRADA DE DIU','extração de aparelho que evita gravidez','205040 EXTRAÇÃO DE APARELHO QUE EVITA GRAVIDEZ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (200,'TELEORIENTAÇÃO','ORIENTAÇÃO POR VÍDEOCONFERÊNCIA','ORIENTAÇÃO POR VÍDEOCONFERÊNCIA',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (201,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (202,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (203,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (204,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (205,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (206,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (207,'TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (208,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (209,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (210,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (211,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (212,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (213,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (214,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (215,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (216,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (217,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (218,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (219,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (220,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (221,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (222,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (223,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (224,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (225,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (226,'   TELEORIENTAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (227,'  TELECONSULTA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (228,'TELECONSULTA','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (229,'TELEORIENTAÇÃO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (230,'CONSULTA POPULAR','COnsulta popular ','000088 CONSULTA POPULAR ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (231,'PRÓTESE','etapa protese','11 ETAPA PROTESE',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (232,'CONSULTA TESTE','Teste interno (comercial)',' TESTE INTERNO (COMERCIAL)',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (233,'TESTE FELIPE ','teste rapido',' TESTE RAPIDO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (234,'BOTOX 5','PCTE 4 APLICAÇÕES',' PCTE 4 APLICAÇÕES',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (235,'MARINA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (236,'SORO 1','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (237,'SORO 1 - AMP 1','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (238,'SORO 1 - AMP 2','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (239,'ECOCARDIOGRAMA- FETAL 2','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (240,'ESPECIAL','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (241,'ASDFFG','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (242,'TESTE TEMPO','teste de tempo procedimento','tt TESTE DE TEMPO PROCEDIMENTO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (243,'ENDOSCOPIA TESTE','endo teste',' ENDO TESTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (244,'AVALIAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (245,'ESPECIAL KARLA','Consulta em consultório (no horário normal ou preestabelecido)','10101012 CONSULTA EM CONSULTÓRIO (NO HORÁRIO NORMAL OU PREESTABELECIDO)',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (246,'','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (247,'CONSULTA','ANTIBIOGRAMA (TESTE DE SENSIBILIDADE E ANTIBIÓTICOS E QUIMIOTERÁPICOS), POR BACTÉRIA - NÃO AUTOMATIZADO','40310418 ANTIBIOGRAMA (TESTE DE SENSIBILIDADE E ANTIBIÓTICOS E QUIMIOTERÁPICOS), POR BACTÉRIA - NÃO AUTOMATIZADO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (248,'CONSULTA CLÍNICA MÉDICA','CONSULTA CLÍNICO GERAL','151515 CONSULTA CLÍNICO GERAL',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (249,'VACINAÇÃO COVID-19','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (250,'TESTE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (251,'CONSULTA CARDIOLÓGICA','CONSULTA EM CONSULTÓRIO (NO HORÁRIO NORMAL OU PREESTABELECIDO)','10101004 CONSULTA EM CONSULTÓRIO (NO HORÁRIO NORMAL OU PREESTABELECIDO)',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (252,'CLINK MED CORAÇÃO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (253,'AVALIACAO CORPORAL','','17548451 ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (254,'TELETESTE','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (255,'PÓS OPERATÓRIO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (256,'001 - PROCEDIMENTO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (257,'002','TESTETESTE','11111122222 TESTETESTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (258,'001 - PROCEDIMENTO','ANTIBIOGRAMA (TESTE DE SENSIBILIDADE E ANTIBIÓTICOS E QUIMIOTERÁPICOS), POR BACTÉRIA - NÃO AUTOMATIZADO','40310418 ANTIBIOGRAMA (TESTE DE SENSIBILIDADE E ANTIBIÓTICOS E QUIMIOTERÁPICOS), POR BACTÉRIA - NÃO AUTOMATIZADO',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (259,'CONSULTA CASSEMS','','10101012 ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (260,'COLOCAÇÃO BALÃO','','40202658 ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (261,'TESTE 222','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (262,'EXAME 01','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (263,'BB GLOW','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (264,'CONSULTA NUTRICIONISTA','CONSULTA NUTRICIONISTA','20212022 CONSULTA NUTRICIONISTA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (265,'ARRANCAR OS BRAÇOS','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (266,'TESTE DE PROCEDIMENTO NOVO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (267,'TESTE PARA PACOTES','TESTANDO A CRIAÇÃO DE UM PACOTE',' TESTANDO A CRIAÇÃO DE UM PACOTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (268,'EXTRAÇÃO DENTE','EXTRAÇÃO DENTE','154 EXTRAÇÃO DENTE',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (478,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (688,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (898,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1108,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1318,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1528,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1738,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (1948,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2158,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2368,NULL,NULL,NULL,1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2369,'PROCEDIMENTOS ESTETICOS','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2370,'CONSULTA SEM PROCEDIMENTO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2371,'CONSULTA COM PROCEDIMENTO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2372,'REAVALIAÇÃO','RETORNO','123456 RETORNO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2373,'ALUGUEL DE SALA','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2374,'VENDA DE PRODUTO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2375,'RETORNO - BOTOX','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2376,'PROCEDIMENTO COM DIAS PARA VOLTA','FEBRE AMARELA, SOROLOGIA','40323331 FEBRE AMARELA, SOROLOGIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2377,'MICROPIGMENTAÇÃO RETORNO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2378,'MICROPIGMENTAÇÃO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2379,'MICRO COMBO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2380,'LIMPEZA DE PELE PROFUNDA COMBO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2381,'OVO','FEBRE DO MEDITERRÂNEO','40323340 FEBRE DO MEDITERRÂNEO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2382,'CONSULTA TESTE','CONSULTA TESTE','515165415 CONSULTA TESTE',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2383,'APLICAÇÃO DE DIU','CONSULTA CONSULTORIO APLICAÇÃO DIU','222222 CONSULTA CONSULTORIO APLICAÇÃO DIU',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2384,'ENDOSCOPIA TESTE','PROCEDIMENTO INVESTIGATIVO','00000003 PROCEDIMENTO INVESTIGATIVO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2385,'TELECONSULTA COVID','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2386,'CONSULTA CARDIO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2387,'31009360 HERNIORRAFIA INGUINAL NA CRIANÇA','HERNIORRAFIA INGUINAL NA CRIANÇA','31009360 HERNIORRAFIA INGUINAL NA CRIANÇA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2388,'HEMOGRAMA','HEMOGRAMA','12 HEMOGRAMA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2389,'CONSULTA TO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2390,'SERVIÇO FARMACÊUTICO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2391,'CONSULTA GERIÁTRICA','CONSULTA DESTINADA A ACOMPANHAMENTO DE IDOSO','12321323 CONSULTA DESTINADA A ACOMPANHAMENTO DE IDOSO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2392,'ABASTECIMENTO','FORNEC. MEDIC. DOENCAS CRONICAS',' FORNEC. MEDIC. DOENCAS CRONICAS',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2393,'MAPA','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2394,'HOLTER','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2395,'MICAELA PROCEDIMENTO','',' ',1,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2396,'SONAX GERAL','SONAX GERAL','1234 SONAX GERAL',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2397,'PROCEDIMENTO MICAELA','UM TESTE','10000 UM TESTE',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2398,'REUNIÃO DE ALINHAMENTO - TI SAÚDE','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2399,'CONSULTA DIEGO','CONSULTA DIEGO','Consulta Diego CONSULTA DIEGO',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2400,'RETIRADA MEDICAMENTOS','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2401,'MASCARA DESCARTAVEIS','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2402,'CONSULTA - DRA ANNA JÚLIA','DRA. ANNA JÚLIA','1 DRA. ANNA JÚLIA',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2403,'ODONTOLOGIA','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2404,'TESTE 333','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2405,'PROCEDIMENTOS ODONTOLOGICOS TESTE','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2406,'RESTAURAÇÃO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2407,'TESTE','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2408,'ELETROCARDIOGRAMA','SEGUIR AS ORIENTAÇÕES ANTES DO EXAME',' SEGUIR AS ORIENTAÇÕES ANTES DO EXAME',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2409,'ACOMPANHAMENTO PARA EMAGRECIMENTO 3 E 6 MESES','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2410,'APLICAÇÃO DE VITAMINA D','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2411,'APLICAÇÃO DE POLI VITAMÍNICO','',' ',0,NULL);
INSERT INTO `` (`id`,`tipo`,`descricao`,`tuss`,`deletado`,`valor`) VALUES (2412,'APLICAÇÃO DE ATIVADOR METABÓLICO','',' ',0,NULL);
