/*
-- Query: select idMedicoNoBdCliente as id, medico, adm, stringEspecialidades as especialidades from tisaude_empresa.usuarios where cliente = 3
-- Date: 2022-06-10 11:25
*/
INSERT INTO `usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (875,1,99,NULL);
INSERT INTO `usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (668,0,99,'');
INSERT INTO `usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (647,1,99,'Gastroenterologista');
INSERT INTO `usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (672,1,99,'Cirurgião plástico');
INSERT INTO `usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (673,1,99,NULL);
INSERT INTO`usuarios` (`id`,`medico`,`adm`,`especialidades`) VALUES (877,1,99,'Farmacêutico, Acupunturista, Angiologista, Ecocardiograma');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (9231,1,99,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (925,1,99,'Farmacêutico, Acupunturista, Alergista e imunologista, Angiologista, Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (923,1,99,'Cardiologista, Clínica Médica');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (970,1,99,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (937,1,99,'Alergista e imunologista, Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (943,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (944,0,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (948,1,1,'Reumatologista, Radiologista, Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (950,1,99,'Médico Hematologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (959,1,99,'Cirurgião dentista - clínico geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (965,1,99,'Acompanhante Terapeuta (AT), Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (963,1,99,'Clínica Médica');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (969,1,99,'Neurocirurgião');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (972,1,99,'Cirurgião dentista - endodontista, Farmacêutico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (973,1,99,'Cirurgião plástico, Psicólogo, Psicanalista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (981,1,99,'Cirurgião dentista - clínico geral, Alergista e imunologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (982,1,99,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (986,1,99,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (988,1,1,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (990,1,1,'Neurocirurgião');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (993,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (994,1,99,'Médico generalista, Cirurgião plástico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1006,1,99,'Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (996,1,99,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (998,1,99,'Cirurgião plástico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (999,1,99,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1001,1,99,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1002,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1003,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1007,1,99,'Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1008,1,99,'Fisioterapeuta');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1010,1,99,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1012,1,99,'Farmacêutico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1017,1,99,'Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1019,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1022,1,99,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1023,1,99,'Acupunturista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1024,1,0,'Psiquiatra');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1026,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1027,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (10,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (11,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (12,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (37,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (2,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (671,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (4,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (5,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (6,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (669,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (876,1,0,'Fisioterapeuta');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1110,1,1,'Dermatologista, Esteticista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (57,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (59,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (62,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (64,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (65,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1111,1,1,'Acupunturista, Alergista e imunologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (68,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (69,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (70,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (892,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (899,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (905,1,1,'Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (895,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (896,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (901,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (904,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (906,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (909,1,0,'Cirurgião dentista - auditor');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (908,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (910,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (911,1,0,'Psicólogo clínico, Cirurgião dentista - clínico geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (912,1,0,'Acupunturista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (913,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (915,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (916,1,0,'Oftalmologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (920,1,1,'Psiquiatra, Cirurgião dentista - auditor');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (924,1,99,'Angiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (926,1,1,'Dermatologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (928,1,0,'Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (929,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (930,1,1,'Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (931,1,99,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (932,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (933,1,1,'Cardiologista, Clínico Geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (934,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (935,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (936,1,1,'Angiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (938,1,1,'Acompanhante Terapeuta (AT)');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1,0,1,'Acompanhante Terapeuta (AT)');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (995,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (940,1,0,'Nutrólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (941,1,99,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (942,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1112,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (945,1,0,'Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (946,1,1,'Dermatologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (947,0,0,'Acupunturista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (951,1,1,'Anestesiologista, Clínico Geral, Nefrologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (952,1,1,'Dermatologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (953,1,1,'Clínico Geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (954,1,1,'Clínico Geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (955,1,99,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (956,1,0,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (957,1,1,'Neurocirurgião, Neurologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (992,0,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (961,1,1,'Clínico Geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (964,1,1,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (966,1,99,'Cirurgião dentista - periodontista, Psiquiatra');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (968,1,99,'');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (971,1,99,'Cirurgião torácico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (3,1,0,'Cirurgião dentista - clínico geral, Cirurgião dentista - odontogeriatra');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (974,1,99,'Cirurgião dentista - clínico geral, Cirurgião dentista - odontogeriatra, Cirurgião do aparelho digestivo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (975,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (976,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (977,1,99,'Cirurgião dentista - clínico geral, Psicólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (978,1,99,'Anestesiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (979,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (980,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (983,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (985,1,0,'Biólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (987,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (989,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (991,1,0,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (997,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1000,1,0,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1005,1,1,'Angiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1014,1,0,'Cardiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1009,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1011,1,1,NULL);
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1013,1,1,'Farmacêutico');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1015,1,1,'Angiologista');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1016,1,1,'Cirurgião geral');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1018,1,0,'Biólogo');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1021,1,0,'Auxiliar de farmácia');
INSERT INTO `` (`id`,`medico`,`adm`,`especialidades`) VALUES (1025,1,1,'Enfermeiro');
